### ISSUE TITLE
Disallow mass assignment for certain variables

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#106]
Model: Comment: Potentially dangerous attribute available for mass assignment: :application_id
Model: Sponsorship: Potentially dangerous attribute available for mass assignment: :user_id
Model: Sponsorship: Potentially dangerous attribute available for mass assignment: :application_id

http://brakemanscanner.org/docs/warning_types/mass_assignment/

**Comment by compwron** [comment]
closing in favor of https://github.com/doubleunion/arooo/issues/396
