### ISSUE TITLE
Do a malware check on application's URLs

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#109]
You can use Google's Safe Browsing Lookup API to check URLs for malware:

https://developers.google.com/safe-browsing/

The lookup API is really simple, although it leaks URLs to Google. But perhaps that is not so important? Because the paranoid API is super annoying.

**Comment by brittag** [comment]
This is a cool idea, but realistically we haven't yet run into problems related to this, and many of us are reading applications in [browsers that already have Safe Browsing integrated](https://www.google.com/transparencyreport/safebrowsing/) (Google Chrome, Mozilla Firefox and Apple Safari). So I'll close this up. :)
