### ISSUE TITLE
Document all the things!

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#111]
We produced some documentation today. Maybe it should go on the wiki or a docs folder. We made some things like:
- [x] data-flow block diagram
- [x] actor & capabilities list
- [ ] formal threat model

**Comment by brittag** [comment]
Do we still have those documents somewhere? Wondering if we should just close this issue.

**Comment by lilliealbert** [comment]
yeah, it's pretty general as-is, although the general spirit of Document all the things! is still very much needed, from a general standpoint and less a security standpoint. For example, writing down all the stuff that you have to do to deploy the app is something that would be real helpful. But also that's different than this issue. Soooooooooo let's close it!
