### ISSUE TITLE
2FA requirements for high-privilege users

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#116]
The coordinator, administrator, and perhaps even keyholders should be asked/required to use 2FA authentication on their Github account.

**Comment by brittag** [comment]
This makes sense to me for anyone with admin power in the app. This is a bit more complex now though, since we allow both Google auth and GitHub auth now - we'd have to check both kinds of auth for 2fa.

**Comment by lilliealbert** [comment]
omg this would be so much work.

I think it came out of the security audit, but I have a real hard time believing it's worth it unless someone had a personal strong desire to do it.

one thing we could do instead is double check with the humans that have admin access that they have 2FA turned on for whatever they auth with?

**Comment by brittag** [comment]
Good point - let's just turn this into a human onboarding checklist item for anyone with admin access on the app. I'll put a note in the document that includes 'new membership coordinator onboarding checklist' in the membership coordinator folder.

**Comment by brittag** [comment]
...and I'll send a note to the board to ask them to double-check this for themselves + put it on their onboarding checklist for new board members. And I think that would close this issue!

**Comment by lilliealbert** [comment]
Yay! GitHub does [have a nice UI](https://github.com/orgs/doubleunion/people) for seeing whether members of the team have 2FA turned on, but it doesn't actually tell us whether they use GitHub for auth. ¯\\\_(ツ)\_/¯
