### ISSUE TITLE
Members should be able to cancel DU membership & Stripe subscription

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#127]
Let's change the "Manage Dues" page to the "Settings" and add a "Cancel DU Membership" button that:

* Cancel the member's Stripe subscription
* Marks the person as a former member
* Emails the membership coordinators

AND if members automatically have Google drive / calendar access, we should probably be dropping them from those, too.

**Comment by brittag** [comment]
I'm going to close this one since I filed a fresh version of it at https://github.com/doubleunion/arooo/issues/242
