### ISSUE TITLE
Membership Coordinators should auth with Google for sharing calendar & docs

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#128]
There should be a second auth for membership coordinators / admins who are accepting applications so that the granting of Google calendar & drive access is done by the person who is authed with Google. Security :+1: 

I'm thinking this fits into the app thusly:
* When the membership coordinator goes to the accept/reject page, there is an Auth with Google button (or auth is just demanded when they go to that page).
* If they aren't authed with Google, clicking the "accept" or "reject" buttons just tells them they have to auth with Google first.
* If they are authed with Google, accepting someone uses the logged-in person's account to grant calendar and google docs access.

This could be built as a secondary app that read from an API if we wanted, I suppose. Or we could just throw it into the Rails app for expedience and see what comes of it later.

----

PS: I'm starting on this with a refactor to add Google auth in general!

**Comment by brittag** [comment]
I'll close this one for the same reason as https://github.com/doubleunion/arooo/issues/53 - granting Calendar/Drive access doesn't take long for a human, so the cost/benefit of engineering this (and getting it done securely) is probably kind of off.
