### ISSUE TITLE
doubleunion.org https issues

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#140]
https://www.doubleunion.org/ works fine, but when I visit https://doubleunion.org/ I get a security cert not trusted since it's serving up the sni.dreamhost.com certificate, and then a 200 OK response with "Site Temporarily Unavailable"

doubleunion.org points to 173.236.227.181 apache2-quack.james-mchenry.dreamhost.com

RapidSSL certificate on main site seems to be for www.doubleunion.org, so would probably need another certificate for the root doubleunion.org to be installed on the dreamhost ip address, as well as whatever httpd config changes that are necessary.

**Comment by r4v5** [comment]
This is an old ticket, so this may be irrelevant or already-know, btu you shouldn't need a second cert for the root; www.doubleunion.org's cert includes the root as a SubjectAltName. (See below) That said, the Dreamhost page (173.236.227.181) doesn't seem to do anything right now except serve a redirect on http; it's not listening on https.
![screen shot 2016-04-14 at 8 49 38 pm](https://cloud.githubusercontent.com/assets/789416/14549114/891b3276-0282-11e6-8a16-46c6bde0abd4.png)

**Comment by brittag** [comment]
Closing this since I can't reproduce the problem; we've probably fixed it in some way since this was filed.
