### ISSUE TITLE
TumblrPost, Vote mass assignment unrestricted?

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#141]
(should be labelled security)

This might also be covered in #112 (mass assignment) or #111 (attribute restriction), but I'm submitting it anyway since it's marked High priority in the brakeman report from early June, and might be good just to have a record that we've cleared it:

Model Warning
Confidence: High
Model: TumblrPost, Vote
Warning Type: Attribute Restriction
Message: Mass assignment is not restricted using attr_accessible

**Comment by compwron** [comment]
There is no longer a TumblrPost model so I think this is safe to close
