### ISSUE TITLE
Links to member websites on /membership use inconsistent protocols

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#155]
Sometimes people include the protocol and sometimes people don't; this means that we end up with links like https://www.doubleunion.org/www.lillie.chilen.com, which isn't a good link.

Maybe we should just add some text asking people to include the protocol.

**Comment by brittag** [comment]
Closing this since this is now filed at https://github.com/doubleunion/doubleunion-dot-org/issues/28
