### ISSUE TITLE
When a voting member steps down, their pending votes should be removed

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#157]
If someone stops being a voting member, their votes should be removed from active applications.

**Comment by brittag** [comment]
I don't know whether we have consensus right now on whether this should happen. I added a note to our Voting Policy doc (in the DU Google Drive) to remind us to look again at this issue next time we have a round of new membership applications.

**Comment by compwron** [comment]
We are looking at potentially having this situation now where a voting member will become unavailable for voting before the end of the voting period. I would like their existing votes to still count, but for the number of required votes to decrease for only candidates that they have not voted on yet. I realize that this is a technically complicated solution. The most flexible solution would be to add a new field on a voting member that is set when they are made a non-voting member which determines whether their old votes count or not. 
Alternately we could add extra admin UI features which make it easy to remove old votes by a non-voting member.

**Comment by brittag** [comment]
We discussed this in a membership committee meeting today, and we decided: if a voting member is unavailable or leaves on good terms, their existing votes should stand. The other voting members should make sure to do their votes to get quorum on each application. This is a simple solution that doesn't involve technical work, so I'll close this thread.
