### ISSUE TITLE
Fix last_stripe_charge_succeeded bug

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#160]
Dummy data on staging is causing this shit to blow up over and over again: 
NoMethodErrorstripe_event/webhook#event
undefined method `last_stripe_charge_succeeded=' for nil:NilClass

https://bugsnag.com/doubleunion/doubleunion/errors/53e86c1f397156561afa7e10#request

**Comment by compwron** [comment]
This is pretty old and the stripe gem has been upgraded and I think it isn't doing this any more, so I am closing the issue.
