### ISSUE TITLE
Add CC BY-SA Double Union to the Base Assumptions

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#161]
There have been requests for other orgs to use our base assumptions or base their own off of them. Let's just add the phrase "[CC BY-SA](https://creativecommons.org/licenses/by-sa/2.0/) Double Union" in italics to the bottom of the list as a new paragraph.

**Comment by brittag** [comment]
This is now an issue for https://github.com/doubleunion/doubleunion-dot-org ! I'll make a PR for this over there.
