### ISSUE TITLE
Remove gem 'machinist' because we are using factory_bot instead

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#176]
We should use only one factory gem. Remove 'machinist'
We are also planning to move from factory_girl (unmaintained) to factory_bot https://github.com/doubleunion/arooo/issues/332

**Comment by compwron** [comment]
This will require changing all the tests that use `.make!` to use the factory_bot style `create(:obj, param: val)` instead, then removing the file`blueprints.rb` and the line `gem 'machinist'` from the `Gemfile`
