### ISSUE TITLE
UX nav updates

### ISSUE THREAD

**Issue by mbecica** [doubleunion/arooo#202]
This is feedback for Vivian's latest website revision: 
![screen shot 2015-05-10 at 1 20 57 pm](https://cloud.githubusercontent.com/assets/409082/7556093/1c65d922-f718-11e4-8ec6-d54b792dcec9.png)
* Turn the "double union" text into our icon - I grabbed the icon from our google docs folder. Keep link around icon image. 
* Top nav should be: Membership, Blog, and About. Move Twitter to the footer.

**Comment by lilliealbert** [comment]
This was finished on the external site.

In the future, issues for the external site (anything **not** at app.doubleunion.org) should be opened on that repo, https://github.com/doubleunion/doubleunion-dot-org.
