### ISSUE TITLE
membership page keymember description update

### ISSUE THREAD

**Issue by ameliagreenhall** [doubleunion/arooo#203]
*Old text:*
Key members also have responsibilities:
- Contribute to the upkeep of the space
- Volunteer for various tasks (e.g., library coordinator!)
- Help uphold the rules of the space
- Come to meetings
- Help shape the space’s direction and future

*New text:*
Key members are responsible for all of the things that members do, plus they also:
- Responsibly lock and alarm the space when leaving as necessary (they get training and documentation on how to do this!).
- Kick people out of the space if they are violating the anti-harassment policy
- Enforce the guest policy as they feel comfortable (not letting someone in the space that is not a member or guest of a member). Check out the guidelines poster in the inside of the DU main door on suggestions on how to do this!
- Take action to stop things if they see something bad happening in the space (say something, call 911, etc.).

Key members also often help open the space for members and events when they can, but it’s not a requirement!

^ last line is not in the bullet points.

**Comment by lilliealbert** [comment]
Did this text change happen? 

In the future, issues for the external site (anything **not** at app.doubleunion.org) should be opened on that repo, https://github.com/doubleunion/doubleunion-dot-org.

**Comment by lilliealbert** [comment]
The text about this on http://www.doubleunion.org/membership has changed enough since this issue was opened that I'm gonna consider it done — feel free to reopen or add a new one if there's more that should be changed.
