### ISSUE TITLE
Problem with 'submit' button on member application

### ISSUE THREAD

**Issue by bwinegarner** [doubleunion/arooo#204]
Error message after clicking 'Submit application': Application not submitted: State cannot transition via "submit."

Happens in Chrome & Firefox on Windows.

**Comment by lizzard** [comment]
Hmmm, we have applications from yesterday but none from today. Maybe something broke last night?

**Comment by lilliealbert** [comment]
It looks like a data problem which I am currently figuring out!

**Comment by brittag** [comment]
This issue was resolved a year ago, so I'll close this up. :)
