### ISSUE TITLE
The new member setup page should note how to apply for a scholarship

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#207]
On [the new member setup page](https://github.com/doubleunion/arooo/blob/master/app/views/members/users/setup.html.haml), "Step Two: Set Up Monthly Dues" should explicitly mention how to apply for a scholarship for dues. It could be something like this, probably right after the "set up dues" button:

"We gladly welcome and support members who can't afford to pay membership dues! That's why any member can request a scholarship due to financial need at any time. There is no waiting period before you can apply for a scholarship or other restriction on when or how often you can ask for a scholarship. **To apply for a scholarship, go to [manage dues](https://app.doubleunion.org/members/users/34/dues)** and fill out the form."

This would be helpful for us to fix before we accept new members so that we make sure everyone hears about the opportunity to get a scholarship. :)

**Comment by lilliealbert** [comment]
Done!  :boom:  c3b7c64c22e34865f8b3a08341eba3b334528ce9

**Comment by brittag** [comment]
Oooooh thanks! It could be slightly better to have the scholarship info after the pink "set up dues" button instead of before it, just for better logical flow, but that's not a blocker.

**Comment by lilliealbert** [comment]
Really? I would think that we would want to explain that they could apply for a scholarship before presenting them with a demand for money.

**Comment by lilliealbert** [comment]
(That is why I put it where I did, but also, I don't care that much, so I'm happy to accept a PR moving it if you or anyone else cares to move it.)

**Comment by lilliealbert** [comment]
PPS: now that I'm re-reading it, the header "Set up dues!" immediately followed by "It's okay not to pay dues!!" is a little silly.

**Comment by brittag** [comment]
Hmm yeah, the story I'm going for is "Hiii cool person, people usually pay dues, so here is how to pay dues, and if you can't pay dues, here is an alternative for you!" Perhaps we could set this up more like this, to be more explicit:

"Step Two: Set Up Monthly Dues"

"Most DU members pay monthly dues, which supports the existence of the space. This is on a sliding scale from $10-100 — you pay the amount that is right for you, and you can change it at any time (up or down) if your financial situation changes. $25 is about average. We also gladly welcome and support members who can't afford to pay membership dues! Any member can request a scholarship due to financial need at any time. To apply for a scholarship, go to the [manage dues page](https://app.doubleunion.org/members/users/34/dues) and fill out the form."

[form to set up dues]

"Email membership@doubleunion.org if you have any questions or concerns about dues."

**Comment by ameliagreenhall** [comment]
That suggested text looks great, Britta!

**Comment by lilliealbert** [comment]
Updated to the new text, @brittag, and deployed!

**Comment by brittag** [comment]
Yay looks great!!!! Thanks Lillie!
