### ISSUE TITLE
Update keymember form to note keycode availability and orientation/meeting requirement

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#214]
Currently when new members join DU, they sometimes see the key member form and immediately fill it out, which is excellent enthusiasm but can lead to a bit of confusion, and we should update the form to make more sense for that membership flow. :)

For reference, the form: https://github.com/doubleunion/arooo/blob/master/app/views/members/statuses/edit.html.haml

First, the page could mention how to get a keycode, since this is relevant information for brand-new members who want access to the space. This could look like this:

    %h1 Get a key code as a member!

    %p [paste the relevant paragraph from the Member Handbook]

    %p Check out the [Member Handbook](link) for more detail about accessing the space, guest policies, and other relevant information.

Then the page could continue with the "Become a key member!" section.

The second part: if a member would like to become a key member, they should meet at least the requirements for getting a keycode, and we could make that explicit in the form with a checkbox labeled something like "I've attended at least two events at DU (including at least one members meeting or orientation), and I've looked through the Member Handbook."

This is open to adjustment and a little bit complex, so I'm filing it as an issue instead of a pull request. :)

(Last month I emailed the board about making the keymember requirements explicitly include the keycode requirement, and one of them responded affirmately that this makes sense.)

**Comment by mbecica** [comment]
My only hesitation on doing this is that we're about to move! So we'll have to readjust our "access to the space" steps - and how it'll be adjusted is still TBD. But conceptually I think this is a good change.

**Comment by brittag** [comment]
Updated link to this form: https://github.com/doubleunion/arooo/blob/master/app/views/members/key_members/edit.html.haml

**Comment by lilliealbert** [comment]
Fixed with e9cf3eed3a2a85bac01049106b0bd3b5c040de44
