### ISSUE TITLE
Change Google Calendar bookmark in app to not link to view-only calendar

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#215]
A new member recently wanted to add an event to the calendar, so she went to the member homepage in the app and clicked the Google Calendar link, and was confused because she could view the calendar but couldn't add to it. That special calendar permalink doesn't allow adding new events.

To avoid confusion, I think we should change this bookmark link to go to the ordinary Google Calendar site (https://www.google.com/calendar/), with a note saying something like "(the DU calendar should display as part of your Google Calendar)".

**Comment by lilliealbert** [comment]
I did this, but it looks kind of odd to me in the context of the whole page. What do you think? Is there another way to present this information?

![screen shot 2016-01-24 at 6 58 48 pm](https://cloud.githubusercontent.com/assets/978428/12541480/8e534eae-c2cc-11e5-935b-ab28eab0e9d4.png)

**Comment by brittag** [comment]
Hmm, I'd change the "DU Members calendar" link to say "Google Calendar" (since it's just a link to generic Google Calendar) and leave the helper text. It does look slightly odd, but it's a slightly odd situation, and at least the updated version won't be confusing. :)

**Comment by brittag** [comment]
Tina looked at this and says the updated version looks fine.

**Comment by brittag** [comment]
Ah, another member just ran into this problem - she asked for calendar edit access, and I checked and she already had edit access - the confusion was that she was viewing this bookmark, which links to a view-only mode. So I'd be in favor of this even if it looks weird. :)

**Comment by brittag** [comment]
Fixed this in https://github.com/doubleunion/arooo/pull/532
