### ISSUE TITLE
Add Gmail filter tip to prevent DU emails going to spam folder

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#216]
On the [Account Setup page](https://github.com/doubleunion/arooo/blob/master/app/views/members/users/setup.html.haml), update the mailing list tip from:

> (We do email a fair amount, so if you don't know about filters and labels and are a gmail user, [have we got a link for you](https://support.google.com/mail/answer/6579?hl=en).)

To this or similar:

> (We do email a fair amount, so if you don't know about filters and labels and are a gmail user, [have we got a link for you](https://support.google.com/mail/answer/6579?hl=en). When you make a filter for your DU mailing list emails, make sure to check the box for "Never send it to Spam"!)

**Comment by lilliealbert** [comment]
Fixed with #225
