### ISSUE TITLE
Put screenshots in the readme or link to them

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#219]
Maybe link to [the announcement blog post](http://doubleunion.tumblr.com/post/101099822404/meet-arooo-a-open-source-membership-management)? Just a note to myself since I noticed the lack of screenshots while showing this to a friend. :)

**Comment by lilliealbert** [comment]
I'm not entirely sure we need them? But maybe I'm a jerk.

**Comment by brittag** [comment]
This occurred to me when I was trying to explain Arooo's features to a friend who helps run a hackerspace and was looking for a new management tool. Not super important, could just be fun. :)

**Comment by lilliealbert** [comment]
Ah, so for sales for people who might use it! I always think of the readme as primarily being for developers, but since Arooo doesn't have a website, the readme is it's de facto home page.
