### ISSUE TITLE
Look into Let's Encrypt for free SSL goodness

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#229]
Right now we're paying $40/month to Heroku for SSL endpoints for our deployment of Arooo and du-dot-org. Maybe we could use Let's Encrypt for free!?!?!

https://letsencrypt.org/

**Comment by brittag** [comment]
Oh excellent point! Let's look into this!!!

**Comment by mathildemouw** [comment]
Based on [this issue on let's encrypt] (https://community.letsencrypt.org/t/lets-encrypt-and-heroku-solved/4272) and [blog post] (http://collectiveidea.com/blog/archives/2016/01/12/lets-encrypt-with-a-rails-app-on-heroku/) it looks like it might not be too complicated to switch our heroku over to using let's encrypt for ssl. I would be interested in helping on this! Would I need to pair with @lilliealbert, or someone else who has access to the heroku account?

**Comment by lilliealbert** [comment]
It turns out we'll still have to pay the $20/month per app to Heroku for the SSL endpoint, so my excitement for this is a bit dampened.

I think I'd rather wait until we have to renew our SSL cert to switch to a free Let's Encrypt cert. Or maybe we should do it now to get it over with. I don't know — SSL configuration has historically been such a huge pain, I'm not super excited about working with it unless I totally have to. And we should definitely wait 'till membership season is done and most of the newly-accepted people have gotten their dues set up so that if we do break everything, it doesn't matter too terribly much.

In terms of who to pair with, yeah, I think I would probably be the correct person to work with.

(Also, that Let's Encrypt issue is really stressful to read! >_< But the blog post is very nice.)

**Comment by brittag** [comment]
I think @lilliealbert already took care of our SSL certs, so I'll close this. :D
