### ISSUE TITLE
Send link of new application instead of whole text

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#240]
Having all the applications in all the current membership's inboxes forever isn't a great thing for privacy. Let's just send out a link to the application!

**Comment by brittag** [comment]
This makes sense to me. Let's keep the application emails pretty much the same at the beginning (subject "There's a new Double Union application!", then "There's a new Double Union application!", then a name with a link to their application) - just cutting it off after the name. The name is helpful for knowing what you're clicking on, but we don't need the full text.
