### ISSUE TITLE
A DU member should be able to cancel their own dues subscription

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#242]
This is filed at https://github.com/doubleunion/arooo/issues/127 - but that issue asks for a bit more.

My current need as a membership coordinator is just for:
- A button that says "I want to cancel my DU membership" on the [Manage Dues page](https://app.doubleunion.org/members/users/34/dues)
- When a person clicks that button, it automatically cancels their Stripe dues subscription (if they have one), and it sends an email to the DU membership coordinator (copying the person) saying "x person wants to cancel their DU membership; please remove their membership and email them when you've removed it".

Then the membership coordinator can manually follow up on removing the person's whole membership.

I'd be happy to sketch out my vision in detail (with specific copy) if that would help. :) I just need this so that we can quickly and respectfully comply with people's requests, rather than the app asking the person to send an email and waiting for the membership coordinator to manually cancel the person's dues subscription.

**Comment by brittag** [comment]
I just saw this, and it might be helpful for working on this: https://github.com/doubleunion/arooo/wiki/Stripe-Dev-Setup :D

**Comment by heyellieday** [comment]
@arbonap and I are currently working on this!

**Comment by brittag** [comment]
🎉  So exciting! Thank you all for working more on this!

**Comment by arbonap** [comment]
@brittag would you like this to also mark the person as a former DU member?

**Comment by heyellieday** [comment]
@arbonap, from what I understand, this feature wouldn't be changing anything but the stripe subscription. Based on this: "Then the membership coordinator can manually follow up on removing the person's whole membership.", I think the membership coordinator would set that status in the app.

Also, @brittag, do you have any preference for the language used when a member successfully cancels their dues? Currently, we just have a notice appear stating "Your dues have now been canceled". If that, or other places with copy need to be certain way, just let us know!

**Comment by lilliealbert** [comment]
If the button says "I want to cancel my DU membership", I would expect it to do more than just cancel the stripe membership — maybe if that's all it does, it should have different text?

I think we also need copy for what actually happens when you click the button.

**Comment by brittag** [comment]
Ooh! I will try to catch up on this over the weekend - my brain is so full of work software during the week. :)

**Comment by carmiendo** [comment]
Also, just saw this -- this now happens! Clicking the 'cancel membership' button cancels dues and sends an email to the membership coordinator to cancel the rest of the membership.

However, the open questions about whether it should do more than that, or whether the text should be different, are very good so I'll leave this open.

**Comment by compwron** [comment]
This currently works. I think that it will be easier for a new developer to figure out what to do here if we close this and open a new issue to work on more changes to the copy and functionality. I created https://github.com/doubleunion/arooo/issues/342 to track this
