### ISSUE TITLE
Show aggregate interests for unsponsored applicants

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#254]
Britta did a cool thing where she read through the unsponsored applications and made a list of snippets of their interests. It could be a fun project to make this a feature of the app! But also not the most straightforward thing, since in order to group things into buckets, you'd need to do some text analysis.

But, dropping this issue in here anyway in case it sounds fun!

**Comment by lwu** [comment]
Thanks! This could be a fun teach people to code project. Anyone want to learn?

**Comment by brittag** [comment]
I'm going to close this since I think it would be really hard to automate this in a helpful way!
