### ISSUE TITLE
Account Setup page has out-of-date text

### ISSUE THREAD

**Issue by carmiendo** [doubleunion/arooo#256]
I'm referring to this page: https://app.doubleunion.org/members/users/1/setup 

The most obvious thing we need to change here is that the mailing list reference is out of date.

But we also are generally using the same email address for the mailing list now as for the google drive/calendar; I set that up by adding the person's email address to the members group, which is also the mailing list. So I think the wording around this should probably be reworked as well.

We should do this before we start accepting members!

**Comment by lilliealbert** [comment]
Can you drop in here what the text should be, and I'll update it?

**Comment by brittag** [comment]
Thanks @carmiendo! Also we always have the issue of people forgetting to fill out the Google-friendly email address box and click "submit" on it, so if anyone has any ideas for further improving that, that would be great too.

**Comment by brittag** [comment]
(And for easy reference, this page is at https://github.com/doubleunion/arooo/blob/master/app/views/members/users/setup.html.haml !)

**Comment by carmiendo** [comment]
Here's my first pass on suggested changes; the doc is set to 'everyone can edit' so go ahead and modify as you wish! I kept my edits marked so that they'd be easy for you to find.

I'm not married to any of this, and while I think it's accurate @brittag, you might be more familiar with the specifics, so please tweak and change if you like!

https://docs.google.com/document/d/1bNXOY-0PIjUC2B-5eT8qRJ4hyRHMFHbokif97G5NSa8/edit#heading=h.ry4f6hycxrgy

**Comment by carmiendo** [comment]
We had some discussion on the above text and I think it's ready to drop in now!

**Comment by lilliealbert** [comment]
woot

**Comment by brittag** [comment]
Heck yeah!! Thank you @carmiendo! 💃
