### ISSUE TITLE
Voting member applicant view: request for more filtering options

### ISSUE THREAD

**Issue by hollyallen** [doubleunion/arooo#261]
The voting member view of member applicants has a large number of useful columns, but when there are many applicants (approaching or exceeding 100) it can be hard to find the applications you want. You can search for one (by name for example) and you can order ascending or descending by a given column. 

It would be helpful to add filtering options. For example: filter out all applications I have voted on, filter out all applications that have enough votes already, filter out all applications that do not have a sponsor, etc.

**Comment by compwron** [comment]
I believe that this has been implemented via sort
