### ISSUE TITLE
Add Google Oauth instructions for development use to README

### ISSUE THREAD

**Issue by mathildemouw** [doubleunion/arooo#266]
It would be more convenient for new member-developers who use google to log in to the app.

**Comment by lyrahall14** [comment]
Ok, I have this problem. Before this, I always used google to log into the DU app. When I open the local instance of the app and try to log in with google, I get the following error message.

![screen shot 2017-06-18 at 5 40 01 pm](https://user-images.githubusercontent.com/29267344/27265594-0c57333e-544d-11e7-984a-ad4aec4666e5.png)

I clicked on the "Learn More" link and it took me to this page:

https://developers.google.com/identity/protocols/OAuth2?csw=1

I assume this problem falls under "using OAuth 2.0 for Web Server applications", so I clicked on that link:

https://developers.google.com/identity/protocols/OAuth2WebServer

From the above page, it seems like the first step is installing the Google API Client Library for Ruby. That is fairly straightforward and can be done by clicking on "Ruby" under the heading "Client Libraries". It tells you to run the command "$ gem install google-api-client" which worked on my setup.

I am not sure of the next step to take. I don't quite understand the first task under the "Prerequisites" header called "Enable APIs for your project". Are APIs enabled for the DU app? If not, how do we enable them?

**Comment by mathildemouw** [comment]
@lyrahall14 It looks like the Google API Client gem has a readme with a lot of info in it that may help you: https://github.com/google/google-api-ruby-client. Thanks for taking a crack at this! Have you been able to get a different error page when you tried logging in with Google auth from you development environment?

**Comment by compwron** [comment]
This would be nice to have, I will try to look into this when I have time.

**Comment by anaulin** [comment]
This was fixed by https://github.com/doubleunion/arooo/pull/458
