### ISSUE TITLE
Heroku git log is out of sync with github

### ISSUE THREAD

**Issue by cachar** [doubleunion/arooo#277]
Our readme says to run `git pull --rebase origin master` before pushing to heroku.

1) Do we expect heroku to be out of sync and require this rebasing, or can we force push the heroku commits to github? If the two are in sync, we shouldn't have to rebase anything when we pull latest github master; the readme could be updated to `git pull origin master`.

2) If we do expect to always have to rebase, `origin` in that command on the readme is confusing; we should update it to `production` or `heroku` or something.

**Comment by compwron** [comment]
I am going to close this because I think that https://github.com/doubleunion/arooo/issues/301 is the right way to fix this.
