### ISSUE TITLE
New member email: add link to register for new member orientations

### ISSUE THREAD

**Issue by judytuna** [doubleunion/arooo#294]
This is a feature request! 
As a membership coordinator, I'd like to be able to use the admin page in the UI of the webapp to insert a link that'll go out in the "Accept" email at the end of a membership drive (for example, 2018's new member orientation link is: https://www.eventbrite.com/e/new-member-orientation-summer-2018-tickets-47493528422 )

**Comment by compwron** [comment]
This has been added but in a non-configurable way. This is also tracked in https://github.com/doubleunion/arooo/issues/336
