### ISSUE TITLE
Error message that prevents some people from submitting applications

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#295]
In certain cases, a prospective member submitting an application will get this error message instead of being able to successfully submit their application: `Application not submitted: State cannot transition via "submit"`

This probably happens in a few different cases, but here's one example that I know of:

1. A person creates and submits an application normally.
2. At the end of the membership application period, the membership coordinator rejects the application because members don't know or haven't met the person, and the membership coordinator sends an email encouraging the person to apply again in the next application period.
3. During the next application period, the person clicks "submit" on a new application.
4. The person gets this error message instead of being able to successfully submit their application. Their application goes nowhere. :cry:

We need to resolve this before the next application period.

**Comment by compwron** [comment]
I fixed this *but* the no votes from the previous application round will remain and I'm not sure whether we want to delete them...

**Comment by brittag** [comment]
All the votes from previous application rounds should be zeroed out when a person reapplies.

**Comment by compwron** [comment]
Ok so just to confirm, we want to to delete previous votes when the person re-applies?

**Comment by brittag** [comment]
Yes, we should delete all previous votes when a person re-applies.

**Comment by Imperiopolis** [comment]
Seems like this would be a good place to use the [paper trail](https://github.com/paper-trail-gem/paper_trail) gem and add tracking on this field so, if we ever really need to, we can go back and review this data

**Comment by brittag** [comment]
@compwron I think you resolved this issue with your change at https://github.com/doubleunion/arooo/pull/303 - if you agree, feel free to close. :D

**Comment by brittag** [comment]
Although it's possible that the report at https://github.com/doubleunion/arooo/issues/317 was the same problem happening again?

**Comment by compwron** [comment]
agreed, closing. thanks!
