### ISSUE TITLE
Add additional documentation specific to DevOps

### ISSUE THREAD

**Issue by gitsteph** [doubleunion/arooo#298]
Open on format; could be like the Member Handbook (in Google Drive) or incorporated into the README, or some other form altogether

**Comment by compwron** [comment]
I am unclear on the requirements here. What is the pain that we want to fix?
I do think that this app could use a runbook and detailled new contributors guide, but I'm not sure whether that's the same.

**Comment by compwron** [comment]
I'm closing this for now because it is not currently actionable but I'm happy to have it reopened if we want to revive the discussion
