### ISSUE TITLE
Create webapp admins without using the heroku console

### ISSUE THREAD

**Issue by carmiendo** [doubleunion/arooo#304]
These are the steps to follow to 'adminify' someone in the webapp:

> Go to a heroku-enabled arooo app directory on your laptop
> Run the command `heroku run rails console` to open the rails console
> Update the user you want to adminify with the code `User.find_by_email(“email@example.com”).update_attribute(:is_admin, true)`

It would be rad if we didn't need to do this manually!

Note, however, that this doesn't happen very frequently, so it doesn't need to be a super conspicuous part of the UI.

**Comment by compwron** [comment]
Done

**Comment by compwron** [comment]
<img width="193" alt="Screen Shot 2019-09-29 at 6 00 19 PM" src="https://user-images.githubusercontent.com/578159/65842821-058b9c80-e2e3-11e9-8656-2a0b51f3f15f.png">
