### ISSUE TITLE
Bug with "enough?" application sorter

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#337]
From the members list: I think that there's something wrong with the application sorter thing because it says that all applications have "enough" votes even though that is not true

**Comment by compwron** [comment]
Probably what we want this to do is sort by type of accepted / not accepted- i.e. has enough of everything, has sponsor, has enough votes, ? We somehow want to make this clearer- otherwise the reader has to just see the numbers and understand them, which is not user-friendly

**Comment by rocketdyke** [comment]
I think the "enough" votes means the recipient has enough votes to either qualify them for admission or disqualify them for admission. From the header:

The "Enough Votes?" column is looking for 5+ yes votes or more than 1 no vote, which is enough votes to make a decision per our application criteria.

**Comment by compwron** [comment]
Closing because I no longer understand this bug
