### ISSUE TITLE
Improve "Account Setup Needed" emails for new members

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#339]
Maybe make the account auto-"finish setup" if google email and dues are both ok?

At least make it clear in the email that if the member is waiting to hear about a scholarship, there is nothing they need to do yet

**Comment by brittag** [comment]
The work to do here is to improve the emails at https://github.com/doubleunion/arooo/tree/master/app/views/new_members_mailer to specifically cover the case of a member who has filled out everything except their dues (because they've applied for a scholarship and it hasn't been approved yet).

**Comment by brittag** [comment]
Resolved the main issue here at https://github.com/doubleunion/arooo/pull/527
