### ISSUE TITLE
Fix sort up/down buttons

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#351]
This was broken by https://github.com/doubleunion/arooo/pull/333

<img width="1095" alt="Screen Shot 2019-06-16 at 4 40 08 PM" src="https://user-images.githubusercontent.com/578159/59571054-702b0c00-9055-11e9-879f-caf91e080477.png">

**Comment by compwron** [comment]
maybe use this fork https://github.com/marlinpierce/jquery-datatables-rails

**Comment by snpd25** [comment]
@compwron , Can I work on this issue?

**Comment by compwron** [comment]
@snpd25 Yep! Thanks! :)

**Comment by snpd25** [comment]
@compwron , I would require a bit of guidance on how to fix this.

**Comment by compwron** [comment]
@snpd25 Are you having trouble 
1. replicating/seeing the issue
2. deciding what the best solution would look like
3. writing the code to implement the solution

1. To see the issue, visit production or staging (staging login info is in the readme)
2. What should the fix be? Show any kind of indicator which implies to the user that the column is sortable- you get to decide! Anything better than the current weird boxes will be a win :)
3. How to write the code- I would start by reading the https://github.com/rweng/jquery-datatables-rails readme and docs and seeing how the arooo code is using it, and trying to see where we're not doing what they recommend

**Comment by snpd25** [comment]
@compwron , actually I am unable to replicate this issue as I am facing problem in setting up the development environment. After running `rake db:create` I get a page-long error message along with `Called from /home/snpd/.rvm/gems/ruby-2.5.5@doubleunion/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in` `load_dependency'
fe_sendauth: no password supplied `Couldn't create database for {"adapter"=>"postgresql", "host"=>"localhost", "encoding"=>"unicode", "database"=>"doubleunion_test", "pool"=>5, "username"=>"postgres", "password"=>nil, "template"=>"template0"}`

**Comment by compwron** [comment]
@snpd25 Hmm, that's not good. The error message seems to say that there is not a password set for the database. In the past that has not been required, which is why it's not in `config/database.example.yml` I recommend setting a database password in your `config/database.yml` and if that works please also update `config/database.example.yml` 
What version of postgres do you have installed? It is possible that newer versions have new requirements. What operating system are you using, and how did you install postgres?

**Comment by snpd25** [comment]
By running this command: `sudo apt install postgresql postgresql-contrib`
I get:
```
postgresql is already the newest version (10+190).
postgresql-contrib is already the newest version (10+190).
```
I am using UBUNTU 18.04
I didn't ever set a password for postgres

**Comment by compwron** [comment]
@snpd25 Are you still having this issue? I recommend setting a password

**Comment by brittag** [comment]
@anaulin Are these buttons still broken? They look ok to me in my local environment.

**Comment by anaulin** [comment]
Yes, this is still broken in production (I just double-checked). Something about the asset paths is not quite the same in production, which is why this breaks there. Feels very low-priority, though.

**Comment by Aiyesha** [comment]
I don't see this in the live website at the moment.  So going to close.  Feel free to reopen if someone is actually seeing this still
