### ISSUE TITLE
When we send a scholarship request, can we cc the person's email (if they've provided it)?

### ISSUE THREAD

**Issue by carmiendo** [doubleunion/arooo#356]
This would serve two purposes:
1 - The person receiving the scholarship would understand that the email has been sent and so forth. (We could also update the email template to include the expectation that they should hear back within two weeks).
2 - We'd like to respond to that person to let them know whether their scholarship has been accepted or not, but we have to go into arooo and look up their email and manually email the person. This would make that process more streamlined and less error-prone.

**Comment by compwron** [comment]
This is very doable
Could you put the current content of that email? It would make this a little easier if you have time

**Comment by carmiendo** [comment]
to: scholarship@doubleunion.org
subject: New DU Scholarship Request

Greetings!

<<NAME>> has requested a scholarship. Here's what they had to say:

<< whatever they wrote on the website >>

Please go to the app and approve or deny this person's scholarship, then email them to let them know. Please also notify the membership coordinator (membership@doubleunion.org) that the person is on the scholarship list, so they can make sure the person's scholarship status is reflected in the membership management system (such as setting them up with Google Drive and Calendar if they're a brand-new member).

Yours Truly, 
Arooo
