### ISSUE TITLE
google group member cleanup

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#357]
This doesn't require any code change but imo it is work that should be tracked, so here we are. :)

Until https://github.com/doubleunion/arooo/issues/342 is worked on, there is the chance that the google group membership can be out of sync with https://app.doubleunion.org membership. I don't know when we last cleaned that up, so I'm doing a batch now. 

Use prod console or https://app.doubleunion.org/admin/memberships.json?locale=en to get all current member info
```
ok_member_emails = User.all_members.map { |user| [user.email_for_google, user.email] }.flatten.compact.map(&:downcase).uniq.sort
```

Download members.csv from https://groups.google.com/a/doubleunion.org/forum/#!managemembers/members/members/active
```
lines = File.open('members.csv').read_lines # download from admin view 
newlines = lines.drop(2) # headers
google_group_members_emails = newlines.map { |l| l.split(',')[0] }.map(&:downcase)
```

Find mystery emails
```
should_delete = google_group_members_emails - ok_member_emails
```

Email draft:
Subject; Double Union email cleanup
```
Hi! This email address has access to the private Double Union google group, but it is not currently associated with an active member account on https://app.doubleunion.org as either a main email or a google-friendly email. 

I will remove this email from the Double Union google group next week on <DATE> unless you email back before then and let me know which https://app.doubleunion.org account it should be linked to. 

Thanks!
```

**Comment by compwron** [comment]
I sent this first email and I will leave this issue open until I actually delete the extra emails from the group.

**Comment by brittag** [comment]
Thanks, this is a great idea!

**Comment by compwron** [comment]
I just sent a second email reminder to the emails from the above query, planned deletion deadline for the 10 emails found above is still 26 June 2019.

**Comment by compwron** [comment]
10 emails removed today
```
ok_member_emails = User.all_members.map { |user| [user.email_for_google, user.email] }.flatten.compact.map(&:downcase).uniq.sort

# irb
lines = File.open('members.csv').readlines # download from admin view
newlines = lines.drop(2) # headers
google_group_members_emails = newlines.map { |l| l.split(',')[0] }.map(&:downcase)
should_delete = google_group_members_emails - ok_member_emails

```
