### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#366]
From slack: https://doubleunion.slack.com/archives/C03SEP6HT/p1562211013005900
Jul 3rd at 8:30 PM
Heya! FYI, Google login is 400-ing for me while attempting to sign in to the app.
note: member 1016

**Comment by compwron** [comment]
Closing because I can't reproduce it

**Comment by compwron** [comment]
Reported again in internal slack https://doubleunion.slack.com/archives/DCTGV721F/p1588358043000500

This issue happens when you use https://app.doubleunion.org instead of https://app.doubleunion.org/?locale=en to log in. This is a real bug and we should fix it by figuring out who has the creds to DU's google auth account and changing the callback url to be the base url.

**Comment by brittag** [comment]
Ana and I can't reproduce this, and it might have been fixed in #461, so we'll close this.
