### ISSUE TITLE
Increase new contributor friendliness

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#371]
I learned some great things at https://www.writespeakcode.com/2019/schedule/ about how to make a repo new-contributor friendly. Here is a list of stuff that I think would be good to do

- add https://allcontributors.org/docs/en/bot/overview or similar (maybe just a Contributors.md file?) to acknowledge and thank contributors
- regular newsletter of changes made and changes wanted
- Tag issues with the "normal" github tag for good first issues: `help wanted` and `good first issue` https://help.github.com/en/articles/helping-new-contributors-find-your-project-with-labels
- DONE have a mailing list https://groups.google.com/a/doubleunion.org/forum/#!forum/public-du-code
- Post about this repo in some (non-toxic) public channels (working on OSS benefits people trying to break into tech- it's not all take and no give to accept non-member contributions!)
-- dev.to discord
-- writespeakcode slack
-- women in tech slack?
- DONE Create PR templates https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository https://github.com/stevemao/github-issue-templates
- Create issue templates https://help.github.com/en/articles/creating-issue-templates-for-your-repository
- DONE get on codetriage ```[![Open Source Helpers](https://www.codetriage.com/doubleunion/arooo/badges/users.svg)](https://www.codetriage.com/doubleunion/arooo)```
- Get on https://up-for-grabs.net by making PR https://github.com/up-for-grabs/up-for-grabs.net#add-a-project https://github.com/up-for-grabs/up-for-grabs.net/pull/1379
- Check out this cool repo and use their ideas https://github.com/legesher/tree-sitter-legesher-python
- Add an Issue template in addition to PR template, based on friendly issue: ushahidi/platform#3531
- Add the #first-timers-only tag (and enforcing it) for things that are almost solved to ensure that more experienced folks don't pick those.
- Add the DU CoC or a link to it to the repo also
- Have a process for people to be assigned issues. ie you have to claim it then you are assigned it, and after X weeks/months of inactivity it will be unassigned?

**Comment by compwron** [comment]
More ideas:
Have a process for people to be assigned issues. ie you have to claim it then you are assigned it, and after X weeks/months of inactivity it will be unassigned.

**Comment by compwron** [comment]
Add the DU CoC or a link to it to the repo also

**Comment by compwron** [comment]
Add the #first-timers-only tag (and enforcing it) for things that are almost solved to ensure that more experienced folks don't pick those.

**Comment by compwron** [comment]
example of friendly issue: https://github.com/ushahidi/platform/issues/3531

**Comment by compwron** [comment]
Check out this cool repo and use their ideas https://github.com/legesher/tree-sitter-legesher-python

**Comment by brittag** [comment]
Thank you @compwron for doing this work! It looks like this is mostly done - I'll close it up since I don't think we have specific remaining work here.
