### ISSUE TITLE
Add August integration to make it easier to add/remove users

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#386]
They have some sort of API it seems like
https://ifttt.com/augusthome
https://developer.amazon.com/blogs/alexa/post/7c9b3937-9f82-49fc-99dd-359d018fb25d/august-home-uses-smart-home-skill-api-for-faster-more-seamless-integration-of-locks-and-cameras
https://medium.com/@nolanbrown/august-lock-rest-apis-the-basics-7ec7f31e7874
https://medium.com/@nolanbrown/the-process-of-reverse-engineering-the-august-lock-api-9dbd12ab65cb
https://github.com/sfiorini/py-august
https://www.npmjs.com/package/august-connect
https://stackoverflow.com/questions/48593242/how-to-convert-string-to-bytestring-in-ajax-post-request
https://github.com/jmaxxz/keymaker/blob/master/postman/august.postman_collection.json

https://api-production.august.com/session
Login and retrieve access token POST https://api-production.august.com/session
Get Houses GET https://api-production.august.com/users/houses/mine
Get Locks GET https://api-production.august.com/users/locks/mine
PUT /locks/adduser/{lockID}/{otherUserId}/{type}

**Comment by anaulin** [comment]
Now that we are no longer in the space and we've returned the August lock to the landlord, this is very low priority. We might or might not ever need this again, depending on what the set up is in the new space.

**Comment by brittag** [comment]
Let's just close this since we gave back our August lock - we can reopen this if we use an August lock in our future space.
