### ISSUE TITLE
Consider updating deployment strategy to be UI based and/or move Travis -> CircleCI? 

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#388]
Do research about whether any of this would be a good idea
Keep in mind the goals: make maintenance easier, while keeping secure and paying minimal $

**Comment by anaulin** [comment]
As part of https://github.com/doubleunion/arooo/issues/428, I've made the app push-button deployable from Heroku for both production and staging, and once the Procfile gets checked in, I'll set it to auto-deploy to `staging`.

Given that we follow a staging -> manual QA -> then production deploy cycle, that seems optimal: deployment to staging will be automatic, and one-click deploys to production are possible after that. So I'd say this is maybe "done" as soon as https://github.com/doubleunion/arooo/issues/428 is complete.

@compwron what do you think?
