### ISSUE TITLE
I18n::InvalidLocalesessions#login

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#394]
This is viewable on bugsnag at https://app.bugsnag.com/double-union/du-arooo/errors/5cd90fcd6e75da001c3377dd?filters[event.since][0]=30d&filters[error.status][0]=open
Events (222)Users (42)
```

I18n::InvalidLocalesessions#login"en UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL#" is not a valid locale2 weeks agoSep 11th, 17:58:09 UTC | production | unhandled
-- | -- | --
```

**Comment by sbpipb** [comment]
is this fixes already?

**Comment by compwron** [comment]
@sbpipb I don't know if this is fixed yet, I don't see it happening in bugsnag anymore so I will close it for now. Thanks for checking!
