### ISSUE TITLE
Update Stripe gems to latest version

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#395]
This is a continuation of https://github.com/doubleunion/arooo/issues/315 

How to do this issue:
```
bundle update stripe stripe-ruby-mock stripe_event # update
rspec # run tests and make sure they work
```
To test: merge, deploy to staging (following readme instructions) and check for errors when changing subscription amounts. 
Then deploy to prod and test by changing your own subscription amount

**Comment by kroyagis** [comment]
I can take this one

**Comment by compwron** [comment]
Sounds good, have fun!

**Comment by sbpipb** [comment]
sounds fun indeed, I'd like to take this on :)

**Comment by compwron** [comment]
Go for it!

**Comment by sbpipb** [comment]
could you assign this issue to me? thanks
