### ISSUE TITLE
add social media links more prominently so members can see them

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#417]
https://www.facebook.com/doubleunion
https://twitter.com/doubleunionsf
https://www.instagram.com/doubleunionsf/

**Comment by ncala** [comment]
i am quite fresh, but i am down to take a stab at this starting next week

**Comment by anaulin** [comment]
Off the top of my head, one obvious place to put these links would be in the view that is shown when you go to https://app.doubleunion.org/members, perhaps in the "Bookmarks" section at the top, which is implemented in this partial: https://github.com/doubleunion/arooo/blob/master/app/views/members/users/_bookmarks.html.haml

@compwron did you have a specific place in mind for adding these links?

**Comment by akp2603** [comment]
Hi there!
Pretty new to open source but have a decent rails experience. Let me know if I can work on it.

**Comment by anaulin** [comment]
Hi @akp2603 ! You are very welcome to work on this, I shall assign it to you.

Seems like one possible place to put these links would be in the "Bookmarks" section on the Members Home page:
![Screen Shot 2020-09-29 at 11 39 48 AM](https://user-images.githubusercontent.com/6729309/94601641-9f648d00-0248-11eb-9809-72edf6efd3db.png)

If you poke around and see other places where you think it might be good to surface these links to members (e.g. maybe in the footer?), feel free to suggest those. The main intent is to make our social media more visible and findable for our members.

The social media links themselves are in the original comment in this issue.

**Comment by the-graytest** [comment]
Hey, I'd love to snag this if I can!

**Comment by anaulin** [comment]
Yes please, go ahead!

>

**Comment by brittag** [comment]
Thanks for offering to help with this! An alternate way to implement this would be to expand the "Double Union | Blog | Twitter" header at the top - to add Facebook and Instagram there, and to also add some little icons to each link to make them more visible as social media links.
