### ISSUE TITLE
upgrade puma from 3 to 4 (used by capybara)

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#429]

**Comment by ircarreira** [comment]
@compwron done in #506 

would you like to consider upgrading to the latest version 5?

**Comment by anaulin** [comment]
@ircarreira we would definitely love to move everything to the newest versions that don't break things and don't involve a lot of work to migrate!

**Comment by brittag** [comment]
The core issue here was resolved in https://github.com/doubleunion/arooo/pull/506, so I'll close this.
