### ISSUE TITLE
update contact email

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#431]
CONTACT_EMAIL        = 'doubleunionsf@gmail.com'
this should probably be the mailing list or something else?

**Comment by anaulin** [comment]
I don't see any references in the code to the constant (cf. https://github.com/doubleunion/arooo/search?q=CONTACT_EMAIL&unscoped_q=CONTACT_EMAIL). Looks like it is maybe unused, and we should remove it from `config/initializers/constants.rb`

**Comment by rahmatullah5** [comment]
@compwron @anaulin can I work on this task? So the constant should be removed from constants.rb ?

**Comment by anaulin** [comment]
Good catch, @rahmatullah5 and yes, you can work on it! I agree, let's remove it altogether, since it's unused. (We can always add it back if/when it is needed.)

**Comment by rahmatullah5** [comment]
@anaulin I'll work on it now. Thanks for assigning me to this issue.

**Comment by rahmatullah5** [comment]
@anaulin @compwron please kindly check my PR #499 

Thanks.

**Comment by rahmatullah5** [comment]
#499

**Comment by rahmatullah5** [comment]
Please kindly check it @anaulin , I'm so sorry because I mention this issue to the wrong repo but I already fix it.

**Comment by anaulin** [comment]
Fixed in https://github.com/doubleunion/arooo/pull/499
