### ISSUE TITLE
Show current app admins on the app (while logged in)

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#449]
The goal of this ticket is for any logged-in member to be able to see who is a current admin, so that there is a transparency about who has admin access and who can be asked for help.

When a member is logged in, they should be able to see, in the members area of the app, a list of the names of the users that have admin access to the app (i.e. has the `admin` flag set to `True` in the database).

**Comment by akp2603** [comment]
Hi @compwron
I am pretty new to open source but have a pretty good experience with rails backend. Can I work on this issue?

**Comment by anaulin** [comment]
@akp2603 yes, you can work on this issue. The Members Home page might be a good place to show this info. Or maybe it is something that could go into the app header or footer. Not sure if @compwron had other specific ideas in mind.

**Comment by brittag** [comment]
![Screen Shot 2020-09-30 at 5 05 13 PM](https://user-images.githubusercontent.com/391313/94752102-1c722e00-033f-11eb-94b3-3db4f3ed472d.png)

Here's a quick mockup of one way to do it. Could be improved a lot, but it'd be a simple way to give this information with a bit of context.

**Comment by akp2603** [comment]
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

Hi @compwron ! just raised a PR. Can you please do the needful?

**Comment by anaulin** [comment]
@akp2603 added topic to repo and reviewed the PR. Thanks for your help!
