### ISSUE TITLE
Don't show application answers by default on the internal profile

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#451]
New members are often surprised that some of their application answers automatically show up on their internal profile on the DU members-only website.

Proposed changes:

* When DU accepts a new member, only their contact information shows by default on their profile page. When they edit their profile, they can see that their answers are pre-filled in content boxes (like the answer to "Why are you interested in joining DU?"). They can click an opt-in checkbox to display their content. They can also edit their content before opting in.

* For current DU members, our content boxes are switched to automatically hidden. If you want to re-enable showing your content, you can click an opt-in checkbox to display it. You can edit your content before opting in.

To figure out: how do we handle in the code for the content boxes that we're going to be asking new members a somewhat different set of questions than we asked existing members?

**Comment by anaulin** [comment]
> To figure out: how do we handle in the code for the content boxes that we're going to be asking new members a somewhat different set of questions than we asked existing members?

I would suggest showing on the profile all the available fields (that the user has opted in, where applicable). This would mean that all users would get the old and the new fields, and the answers to some might be empty (depending on which application they answered). This feels straightforward to implement, even if it is not the most perfectly elegant solution.

@brittag how does this sound to you?

**Comment by brittag** [comment]
That sounds good to me, thank you!

**Comment by anaulin** [comment]
Resolved in https://github.com/doubleunion/arooo/pull/580
