### ISSUE TITLE
http://app.doubleunion.org/login should redirect to HTTPS

### ISSUE THREAD

**Issue by anaulin** [doubleunion/arooo#461]
If you try to log using Google OAuth from http://app.doubleunion.org/ (notice that this URL is http, not httpS), you get a 400 error, because Google correctly expects the callback to be HTTPS.

We should redirect folks to the HTTPS version of the site whenever they land on HTTP, both for privacy and security, and to avoid this login confusion.

(A member ran into this and reported it to the Membership Coordinator.)

Screenshot of the Google Auth error that appears if you try to log in from the non-HTTPS URL:
![Screen Shot 2020-07-10 at 9 05 35 PM](https://user-images.githubusercontent.com/6729309/87216099-27de2c00-c2f1-11ea-9aa4-e4c464b01b49.png)

**Comment by anaulin** [comment]
This might be either the same bug, or something very related to what was reported in https://github.com/doubleunion/arooo/issues/366

**Comment by akp2603** [comment]
Hi @anaulin , would like to look into this. Can you assign me this one?
