### ISSUE TITLE
Nil user.application.processed_at on staging causes exception

### ISSUE THREAD

**Issue by anaulin** [doubleunion/arooo#463]
This doesn't seem urgent or severe, but it would be nice to fix.

Reported by Bugsnag. Once a day, when `scheduler:setup_reminder_emails` runs on staging, we get an exception:
```
app/service_objects/account_setup_reminder.rb:9:in `block in send_emails': undefined method `<' for nil:NilClass (NoMethodError)
```

Which seems to be coming from this code:
```ruby
#app/service_objects/account_setup_reminder.rb
[...]
  def send_emails
    @users.each do |user|
      processed_at = user.application.processed_at
      if processed_at < 2.days.ago && processed_at > 4.days.ago
[...]
```
Bugsnag report with more details: https://app.bugsnag.com/double-union/du-arooo-staging/errors/5ea3539fcaaab10018c9cffa?filters[event.since][0]=30d&filters[error.status][0]=open 

Not sure if this is data that is malformed, and we shouldn't allow this date to be nil, or if this code should be able to handle a nil `processed_at`. A quick first-order fix would be to make the code resilient to the `processed_at` being `nil`.

**Comment by RajivSah** [comment]
Can I work on it?

**Comment by anaulin** [comment]
Looks like this is now successfully fixed. Thank you, @RajivSah ! 😻 

![Screen Shot 2020-09-28 at 6 41 41 PM](https://user-images.githubusercontent.com/6729309/94503005-4e0dbc80-01ba-11eb-9929-f30ef0c0a7ba.png)
(screenshot from our acceptance Bugsnag dashboard)
