### ISSUE TITLE
Remove internationalization support and non-english text from app

### ISSUE THREAD

**Issue by anaulin** [doubleunion/arooo#484]
As part of the membership drive restructuring, we've decided to no longer support applications in languages other than English. While we want to be as inclusive and accessible as possible, we simply do not have the peoplepower to maintain questions and infrastructure in different languages. DU is at the moment a space with English as its primary language, as is this app, so realistically members and applicants will need to be minimally comfortable with the language.

As part of this work we would:
* remove all the non-English text (from https://github.com/doubleunion/arooo/tree/master/config/locales)
* migrate English text from `en` locale file into the relevant views, to make it easier to see the text in context
* remove or turn off Rails' locale support, if that's a thing that's easy to do

**Comment by kevinluo201** [comment]
May I try this?
What this issue want is to remove i18n, right?

**Comment by brittag** [comment]
@kevinluo201 Sure! Yes, we need to remove the internationalization support. It's a feature we don't need anymore, so removing it will help us simplify our code and content maintenance.
