### ISSUE TITLE
Use CanCanCan for finer-grained admin authorization

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#50]
Currently, anyone with is_admin set to true can access the Manage Applications and New Members pages. Since there are now different sets of people doing the jobs of helping applicants and helping new members, it would be nice to have finer-grained access control — instead of giving everyone admin rights to everything, have specific roles for application coordinators and new member coordinators.

Roles:

admin — can do everything
application_coordinator — can see manage application page, can accept/reject applications 
member_coordinator — can see manage members page + all the things on it, can see new members page + all the things on it

Some people will need both application & member coordinator roles, so that's neat.

Use [CanCanCan](https://github.com/CanCanCommunity/cancancan).

**Comment by brittag** [comment]
We currently have just one set of people helping applicants and new members (membership coordinators), so this is probably no longer something we need. :)
