### ISSUE TITLE
Figure out how to get SSL working correctly in tests

### ISSUE THREAD

**Issue by anaulin** [doubleunion/arooo#503]
During work on https://github.com/doubleunion/arooo/pull/502 we ran into issues with Capybara not playing nice with HTTPS in tests. We worked around this by disabling the redirect in tests, but it would be nice to be able to re-enable the redirect in tests, and get everything working nicely.

The goal of this ticket is to be able to remove the conditional that removes HTTPS redirection in tests, and have all specs pass.

See https://github.com/doubleunion/arooo/pull/502 for details of the errors that we saw, and where this redirect is.

**Comment by ircarreira** [comment]
Addressed in #508. Please let me know if it fulfils your requirement well. In my experience this is simplest and cleanest way to support the automatic SSL redirection in production like environments.

**Comment by ircarreira** [comment]
I feel it's worth noting that it's uncommon using a `force SSL` kind of setting in development and automated test environments - which means we don't need to worry about handling certificates
