### ISSUE TITLE
500 error due to member's stripe customer not having a "plan"

### ISSUE THREAD

**Issue by anaulin** [doubleunion/arooo#504]
Reported via Bugsnag:
<img width="835" alt="Screen Shot 2020-10-18 at 11 58 44 AM" src="https://user-images.githubusercontent.com/6729309/96377254-6f1e5900-1139-11eb-8265-835555d6e745.png">

Off the top of my head, this could happen e.g. if a member is on scholarship, but we still have a stripe customer id for them. A simple fix for this might be early returning in this block if there is no active subscription.

**Comment by ircarreira** [comment]
@anaulin happy to help. please feel free to let me know if you had a different kind of fix in mind
