### ISSUE TITLE
Upgrade Rails to stop getting deprecation warnings with Ruby 2.7

### ISSUE THREAD

**Issue by anaulin** [doubleunion/arooo#507]
With the current combination of Ruby and Rails versions we're using, we get lots of deprecation warnings. This is because our chosen version of Ruby is "too new" (i.e. not really supported) for the version of Rails we're using. Would be nice to move to a newer Rails version, which would both clean up the deprecation warnings, and keep us up-to-date on the Rails upgrade train.

**Comment by katafrakt** [comment]
I have done something similar recently (upgrade from 5.2 to 6.0), I'll have a look.

**Comment by anaulin** [comment]
Thank you, @katafrakt ! Let me know if you have any questions.
