### ISSUE TITLE
Rename "Manage Dues" to "Manage Membership"

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#514]
A member recently asked me how to cancel their membership, and I explained that you go to the "Manage Dues" page in the DU webapp, and that made me realize we should rename it - it'd make more sense to tell them to go to "Manage Membership".

There are a few places where we'd need to rename this, including checking our internal Member Handbook and other documents for references to "Manage Dues".

We should also make more clear near the top of the page (like a table of contents) that this is where you can cancel your membership as well.

**Comment by compwron** [comment]
Seems like a good idea :)
