### ISSUE TITLE
Replace "master" branch with "main"

### ISSUE THREAD

**Issue by anaulin** [doubleunion/arooo#526]
`main` is now the default naming for the "base branch" of GitHub repos, and is a better name. We can replace our existing `master` branch with `main` by:
* create a new `main` branch
* change GitHub settings to use `main` as the base branch (here: https://github.com/doubleunion/arooo/settings/branches)
* delete `master` branch
* update Heroku deploys to be from `main` branch (here: https://dashboard.heroku.com/apps/doubleunion-staging/deploy/github and here: https://dashboard.heroku.com/apps/du-arooo/deploy/github)

**Comment by carlyrobison** [comment]
Main should be the default now.
