### ISSUE TITLE
Use Google scripts to grant Docs and/or Calendar access programmatically

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#53]
When someone is accepted, they fill out a form saying what email address we should share the Google docs & calendar with. We should figure out how to use computers to share those things automatically when that form is submitted, instead of having humans do it by hand.

**Comment by brittag** [comment]
This is a lovely idea, but this isn't a big pain point for me as a membership coordinator - it doesn't take long to add people to Google Calendar / Google Drive / Slack. Also, I only add new members to those services after they set up dues or scholarship status - so this is a somewhat complex system.

It doesn't seem worthwhile to invest a lot of engineering effort into trying to integrate / automate all these things; there are other aspects of the app that I'd rather see improved first. :D

**Comment by lilliealbert** [comment]
🎉
