### ISSUE TITLE
Able to submit application with blank answers despite them being labeled "required"

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#565]
**What is the problem, and what should happen instead?**

When I submitted a test application yesterday, I left the answers to the three essay questions blank, and the system allowed me to submit the application like that. These three questions are marked "required".

It's important for these to be required fields, because we can't successfully review an application with blank essay answers.

It should be possible to "save without submitting" without filling out those answers, but it shouldn't be possible to "submit" without filling them out.

**Figure out:**

Is this because it wants to allow you to save without submitting? Can we make it so that you can save without submitting without filling out all the required material, but you can only submit if you fill out all the required material?

**Comment by brittag** [comment]
Carly looked at the code, and there's no logic currently for making sure required fields have data in them.

**Comment by anaulin** [comment]
Fixed in https://github.com/doubleunion/arooo/pull/570
