### ISSUE TITLE
Add a way for admins to temporarily disable email sending in the app

### ISSUE THREAD

**Issue by anaulin** [doubleunion/arooo#572]
For testing the application flow, it would be good to be able to temporarily disable sending automated emails to voting members.

We might be able to do this by adding another option to the Configure App section (https://app.doubleunion.org/admin/configurable).

**Comment by anaulin** [comment]
Also related, or maybe an easy way to accomplish this: revise the list of people that these emails get sent to. Should this list be cleared in preparation for re-opening the whole process?

**Comment by brittag** [comment]
I believe currently each new application causes an email to all members, not just members. And yeah, it's a good question whether this makes sense - the idea is to encourage everyone to comment on applications, but it's a lot of email. A weekly digest to all members might be a more reasonable idea.
