### ISSUE TITLE
Can't see "become a key member" button

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#605]
**What is the problem, and what should happen instead?**

On the "Members Home" page, I should see the "become a key member" button because I am currently not a key member according to the web app, but I don't see it. I just have the "become a voting member" button.

I think that this is because I am already assigned a door code. Ana and I briefly discussed this already, just filing it to keep track of it.

**Screenshots of current behavior, if any**

![Screen Shot 2022-01-03 at 8 09 38 PM](https://user-images.githubusercontent.com/391313/148008457-39a3107a-d966-4c15-ba91-47152f64abe0.png)

This is my row in the Admin Membership Console:

![Screen Shot 2022-01-03 at 8 10 21 PM](https://user-images.githubusercontent.com/391313/148008488-28f2847d-c5ed-4a7a-8e0f-2467dfb73d15.png)

**Comment by anaulin** [comment]
This got messed up by my changes in this commit: https://github.com/doubleunion/arooo/commit/03b005afe815cc8045b15e2d7c35e80bce6a0c26

I'll try to make a minimal change to bring it back to the state it used to be in before my change.
