### ISSUE TITLE
Put a box around member profile / application question answer markdown text boxes

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#74]
Currently, you can put ````<h1>```` content in your Markdown, which just sorta floats under the section heading, which is an ````<h2>````.  Kinda confusing.  Putting a box around the content is probably the easiest way to demarcate it.

**Comment by brittag** [comment]
We could maybe have `<hr>`s instead of boxes - https://github.com/doubleunion/arooo/pull/197#issuecomment-64932708 - but basically we haven't run into this problem in the last couple rounds of applications, so I'm thinking it's likely not something we need to mess with. :)
